### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by CmdLnInt** [tecywiz121/freeboard-flot#4]
Is it possible to plot historical data but still keep the graph realtime. ie plot the last 24hrs data on loading and then keep the graph up to date?

**Comment by tecywiz121** [comment]
Yes, that is possible, and in fact how I'm using it, but that is something you'll have to include in your data source. The display widgets don't really get much access to the data.

Take a look at http://freeboard.github.io/freeboard/docs/plugin_example.html

**Comment by CmdLnInt** [comment]
Any chance you could share your data source?

**Comment by tecywiz121** [comment]
It's for a specific product, so I doubt it'll be much use to you. The basic idea is that you call the [`updateCallback`](http://freeboard.github.io/freeboard/docs/plugin_example.html#section-24) repeatedly until you run out of historical data, then start the interval to receive the live data.
