### ISSUE TITLE
Static Data

### ISSUE THREAD

**Issue by CmdLnInt** [tecywiz121/freeboard-flot#5]
I tried to plot some static data by just adding the following array without using a datasource plugin, but I get unexpected results. A few lines all different colours and a few different colour dots?

[[1999, 3.0], [2000, 3.9], [2001, 2.0], [2002, 1.2], [2003, 1.3], [2004, 2.5], [2005, 2.0], [2006, 3.1], [2007, 2.9], [2008, 0.9]]

**Comment by tecywiz121** [comment]
Freeboard only really deals with snapshots of the current data. Each item in the array is actually a separate line, and you need to generate multiple snapshots to get multiple points on the same line.

For example:

``` javascript
[
    [0, 5],
    [0, 10],
    [0, 15],
]
```

This data will create a graph with 3 points. One yellow point at (0, 5), one red point at (0, 10), and one blue point at (0, 15). Each point will be on its own line.

If you want to have some static data displayed, you'll have to create your own freeboard data source plugin to provide it.
