### ISSUE TITLE
Extended Fork

### ISSUE THREAD

**Issue by stufisher** [tecywiz121/freeboard-flot#6]
Just to let you know i've forked this and created a new plugin based on it. I didnt want to fork directly as i've changed how it works internally. It now plots flot data structures directly as im using it in conjunction with nodered, rather than working as a fifo. 

Adds lots of new plot types and other flot features like zooming and tooltips, feel free to steal features back: https://github.com/stufisher/freeboard-flot-extended

**Comment by tecywiz121** [comment]
Hey, that's pretty cool! I'll add a link.
